name: Deploy environments to GitHub Pages

on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  validate:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    uses: ./.github/workflows/validate.yml

  deploy:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    needs: validate
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.event_name == 'workflow_dispatch' && github.ref_name == 'main' || github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') && 'production' || 'staging' }}
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Prepare Pages artifact
        run: |
          mkdir public
          cp -r environments/staging public/staging
          cp -r environments/production public/production
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
