name: deploy-workflow

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pre-deploy-validation:
    uses: ./.github/workflows/validate-application.yml

  deploy:
    needs: pre-deploy-validation
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Prepare Pages artifact
        run: |
          mkdir public
          cp -r environments/staging public/staging
          cp -r environments/production public/production
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
